# Generated by Django 5.2.6 on 2025-10-12 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_publication_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='average_rating',
        ),
    ]
