# Generated by Django 5.2.3 on 2025-06-25 11:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qrcode',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='qr_codes/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='mobile_number',
            field=models.CharField(max_length=11),
        ),
    ]
