# Generated by Django 5.2.3 on 2025-06-26 19:08

import django.core.validators
import django.db.models.deletion
import scanner.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_qrcode_created_at_qrcode_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCodeUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('generated', 'Generated'), ('scanned', 'Scanned'), ('failed_scan', 'Failed Scan'), ('expired', 'Expired')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('additional_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='qrcode',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='qrcode',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether still valid'),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional metadata'),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='qr_id',
            field=models.CharField(default=scanner.models.generate_qr_id, help_text='Unique identifier for the QR code', max_length=36, unique=True),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='qr_type',
            field=models.CharField(choices=[('payment', 'Payment'), ('verification', 'Verification'), ('access', 'Access Control'), ('info', 'Information')], default='payment', max_length=50),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='scan_count',
            field=models.PositiveIntegerField(default=0, help_text='Times scanned'),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='scanned_at',
            field=models.DateTimeField(blank=True, help_text='When scanned', null=True),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When generated'),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='data',
            field=models.TextField(help_text='The main data/content encoded in the QR code'),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='image',
            field=models.ImageField(help_text='QR code image file', max_length=255, upload_to=scanner.models.qr_image_upload_path),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='mobile_number',
            field=models.CharField(help_text='11-digit mobile number starting with 03', max_length=11, validators=[django.core.validators.RegexValidator(message='Must be 11 digits starting with 03', regex='^03\\d{9}$')]),
        ),
        migrations.AddIndex(
            model_name='qrcode',
            index=models.Index(fields=['qr_id'], name='scanner_qrc_qr_id_9e6eaf_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcode',
            index=models.Index(fields=['mobile_number', 'is_active'], name='scanner_qrc_mobile__4fccb4_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcode',
            index=models.Index(fields=['created_at'], name='scanner_qrc_created_8908b6_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcode',
            index=models.Index(fields=['qr_type', 'is_active'], name='scanner_qrc_qr_type_525464_idx'),
        ),
        migrations.AddField(
            model_name='qrcodeusagelog',
            name='qr_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='scanner.qrcode'),
        ),
        migrations.AddIndex(
            model_name='qrcodeusagelog',
            index=models.Index(fields=['qr_code', 'action'], name='scanner_qrc_qr_code_c98d9d_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcodeusagelog',
            index=models.Index(fields=['timestamp'], name='scanner_qrc_timesta_d2c40b_idx'),
        ),
    ]
