# Generated by Django 5.2.2 on 2025-06-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_profile_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.IntegerField(default='Pakistan', max_length=100),
        ),
    ]
