# Generated by Django 5.2.2 on 2025-06-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_profile_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.IntegerField(max_length=100),
        ),
    ]
