# Generated by Django 5.2.4 on 2025-07-13 08:12

import django.core.validators
import student.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=1)),
                ('locality', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pin', models.PositiveIntegerField(help_text='Enter a 6-digit PIN code', validators=[student.models.validate_pin_length])),
                ('state', models.CharField(choices=[('sindh', 'Sindh'), ('punjab', 'Punjab'), ('kpk', 'Khyber Pakhtunkhwa'), ('balochistan', 'Balochistan'), ('gilgit', 'Gilgit-Baltistan'), ('islamabad', 'Islamabad'), ('azad_kashmir', 'Azad Kashmir')], default='sindh', max_length=20)),
                ('mobile', models.CharField(help_text='Enter a valid mobile number', max_length=15, validators=[django.core.validators.RegexValidator(regex='^\\d{15}$')])),
                ('email', models.EmailField(max_length=254)),
                ('job_city', models.CharField(max_length=100)),
                ('profile_image', models.ImageField(blank=True, upload_to='profile_images/')),
                ('my_file', models.FileField(blank=True, upload_to='files/')),
            ],
        ),
    ]
